name: shared_data
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  isar: ^3.1.0+1
  shared_domain:
    path: ../shared_domain
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9
