name: domain
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  mockito: ^5.4.4
  shared_domain:
    path: ../../shared_feature/shared_domain

dev_dependencies:
  build_runner: ^2.4.9
  test: ^1.25.5
  lints: ^2.1.0
