name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  mockito: ^5.4.4
  shared_domain:
    path: ../../shared_feature/domain
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.9
  lints: ^2.1.0
  test: ^1.24.0
