name: Run test

on: 
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'

      - name: Get Dependencies
        run: flutter pub get

      - name: Testing presentation on Home Feature
        run: flutter test -- ./home_feature/presentation
