name: Run test

on: 
  pull_request:

jobs:
  calendar_feature_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'

      - name: Testing presentation
        working-directory: ./calendar_feature/presentation
        run: flutter test -j 1

      - name: Testing domain
        working-directory: ./calendar_feature/domain
        run: dart pub run build_runner build && dart test -j 1

      - name: Testing data
        working-directory: ./calendar_feature/data
        run: dart pub run build_runner build && dart test -j 1